---
###############################################################################
#
# Oracle 12c のインストールに必要なパッケージ
#
###############################################################################
- hosts: all

  tasks:
    - name: yum update
      shell:  yum update -y
    - name: yum install 
      yum: name={{ item }} state=present
      with_items:
        - binutils
        - compat-libcap1
        - compat-libstdc++-33.i686
        - compat-libstdc++-33
        - gcc-c++
        - glibc.i686
        - glibc
        - glibc-devel.i686
        - glibc-devel
        - ksh
        - libaio.i686
        - libaio
        - libaio-devel.i686
        - libaio-devel
        - libgcc.i686
        - libgcc
        - libstdc++.i686
        - libstdc++
        - libstdc++-devel.i686
        - libstdc++-devel
        - libxcb.i686
        - libxcb
        - libX11.i686
        - libX11
        - libXau.i686
        - libXau
        - libXi.i686
        - libXi
        - libXtst.i686
        - libXtst
        - make
        - net-tools
        - smartmontools
        - sysstat
